export const CHANGE_MAIN_TAB = "CHANGE_MAIN_TAB";
export const CHANGE_WEAPON = "CHANGE_WEAPON";
export const CHANGE_ARMOR = "CHANGE_ARMOR";
export const CHANGE_SETTINGS = "CHANGE_SETTINGS";
export const CHANGE_STATS = "CHANGE_STATS";
export const CHANGE_DAMAGE = "CHANGE_DAMAGE";
export const CHANGE_RESISTANCE = "CHANGE_RESISTANCE";
export const CHANGE_LIMBS = "CHANGE_LIMBS";