export const CHANGE_MAIN_TAB = "CHANGE_MAIN_TAB";
export const CHANGE_WEAPON = "CHANGE_WEAPON";
export const CHANGE_ARMOR = "CHANGE_ARMOR";
export const CHANGE_SETTINGS = "CHANGE_SETTINGS";
export const CHANGE_STATS = "CHANGE_STATS";